import fs from "node:fs";
import { caricaConfig } from "../config.ts";
import { creaFile } from "../file-claude.ts";
const config = caricaConfig();
const rapporto = fs.readFileSync(process.argv[2], "utf8");
const t = Date.now();
const f = await creaFile(config, { tipo: "pdf", nomeFile: "prova-ricerca", istruzioni: `Impagina il rapporto (file rapporto.md, in Markdown) come PDF professionale: copertina con titolo "Bot di moderazione AI per community", data 2026-10-09 e "Ricerca di Jarvis per Doublegram"; indice; titoli, elenchi e tabelle curati; numeri di pagina; fonti in fondo con link cliccabili. Il testo va riportato fedelmente e per intero.`, allegati: [{ nome: "rapporto.md", testo: rapporto }] }, (p) => console.log(Math.round((Date.now()-t)/1000)+"s", p));
fs.writeFileSync(process.argv[3], f.dati);
console.log("OK", f.nome, f.dati.length, Math.round((Date.now()-t)/1000)+"s");
console.log(f.nota);
